# Generated by Django 3.2.8 on 2021-10-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumes',
            name='composition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='jeans',
            name='composition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='outerwear',
            name='composition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='composition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='sweatshirts',
            name='composition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Состав'),
        ),
    ]
